platform:ios, '8.0'

target 'SeriesGuide' do  #工程名称
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SDWebImage', '~> 4.1.0'
    pod 'FMDB', '~> 2.7.2'
    pod 'Masonry'
    pod 'ReactiveObjC'
    pod 'MJExtension', '~> 3.0.13'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'CAUMessage', '~> 1.3.0'
    pod 'UMengAnalytics'
    pod 'UMengUShare/Social/ReducedWeChat'
    pod 'UMengUShare/Social/ReducedQQ'
    pod 'UMengUShare/Social/ReducedSina'
    pod 'WechatOpenSDK'
    pod 'KeyboardToolBar'
    pod 'SAMKeychain'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'SVProgressHUD','2.0.3'
    pod 'MarqueeLabel', '~> 2.2.0'
    pod 'YYText'
    pod 'SDCycleScrollView', '~> 1.75'
    pod 'JHChart'
    pod 'WYChart'
end
